{
 "title": "ConfD Performance Measurement Demo",
 "description": "CPU and Memory Usage",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "ConfD",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 5, "y": 0 },
   "targets": [
    { "expr": "confd_cpu_usage" }
   ]
  },
  {
   "title": "ConfD",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 5, "x": 9, "y": 0 },
   "targets": [
    { "expr": "confd_rss", "legendFormat": "RSS {{process}}" }
   ]
  },
  {
   "title": "ConfD",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 5, "x": 14, "y": 0 },
   "targets": [
    { "expr": "confd_hvm" }
   ]
  },
  {
   "title": "ConfD CPU Usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 4 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    { "expr": "confd_cpu_usage", "legendFormat": "CPU {{process}}" }
   ]
  },
  {
   "title": "ConfD Memory Usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 4 },
   "yaxes": [
    { "format": "deckbytes" }
   ],
   "targets": [
    { "expr": "confd_rss", "legendFormat": "RSS {{process}}" },
    { "expr": "confd_hvm", "legendFormat": "HWM {{process}}" }
   ]
  },
  {
   "title": "ConfD Wall Clock Time Measurment of Getting and Setting XML Configuration Data",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    { "expr": "confd_test_time", "legendFormat": "{{test}} {{num}}" }
   ]
  },
  {
   "title": "ConfD High Watermark Memory Measurement of Setting and Getting XML Configuration Data",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "confd_test_hvm", "legendFormat": "{{test}} {{num}}" }
   ]
  },
  {
   "title": "ConfD RSS End of Test Memory Measurement of Setting and Getting XML Configuration Data",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "deckbytes" }
   ],
   "targets": [
    { "expr": "confd_test_rss", "legendFormat": "{{test}} {{num}}" }
   ]
  }
 ]
}