/*
 * BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
 * This file has been auto-generated by the confdc compiler.
 * Source: example.fxs
 * BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
 */

#ifndef _EXAMPLE_H_
#define _EXAMPLE_H_

#ifdef __cplusplus
extern "C" {
#endif /* __cplusplus */

#ifndef example__ns
#define example__ns 1551726738
#define example__ns_id "http://tail-f.com/ns/example/config"
#define example__ns_uri "http://tail-f.com/ns/example/config"
#endif

#define example_obj 1719948295
#define example_nod4 1861273480
#define example_nod2 1105445312
#define example_name 1998270519
#define example_nod1 1075662437
#define example_nod3 457096503

#ifdef __cplusplus
}
#endif

#endif
