/*
 * BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
 * This file has been auto-generated by the confdc compiler.
 * Source: dhcpd.fxs
 * BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
 */

#ifndef _DHCPD_H_
#define _DHCPD_H_

#ifdef __cplusplus
extern "C" {
#endif /* __cplusplus */

#ifndef dhcpd__ns
#define dhcpd__ns 1946994318
#define dhcpd__ns_id "http://tail-f.com/ns/example/dhcpd"
#define dhcpd__ns_uri "http://tail-f.com/ns/example/dhcpd"
#endif

#define dhcpd_log_facility 2049412155
#define dhcpd_name 1998270519
#define dhcpd_subnet 1544472008
#define dhcpd_range 28853268
#define dhcpd_dhcp 990408299
#define dhcpd_net 872020178
#define dhcpd_mask 1167181041
#define dhcpd_subnets 1650094351
#define dhcpd_kern 0
#define dhcpd_local7 2
#define dhcpd_routers 1226429584
#define dhcpd_shared_networks 511577759
#define dhcpd_shared_network 256078062
#define dhcpd_mail 1
#define dhcpd_high_addr 218505843
#define dhcpd_dynamic_bootp 29929361
#define dhcpd_max_lease_time 1794251668
#define dhcpd_low_addr 2122895953
#define dhcpd_default_lease_time 1186076854

#ifdef __cplusplus
}
#endif

#endif
